### PR TITLE
feat(project): add TypeScript definitions

### PR DESCRIPTION
**Pull request by nikeee**
This PR adds type definitions to the NPM package. Then TS users are installing this package, they should get type checking automatically.

### CODE REVIEW

**Comment by nikku** [comment]
Just wondering, how do you generate these definitions? By hand? How are we supposed to update them?

**Comment by nikeee** [comment]
They were written by hand. One can generate parts of it, but the result is not very satisfying.

Basically, if something changes, you copy the signature of the function and annotate them with JavaScripts's types. If more specific ones are required, one can look at the lib.d.ts files located here:
https://github.com/Microsoft/TypeScript/tree/master/lib

One should distinguish between nullable and undefinable types. If one writes `a: string`, that does not mean that the string can be `null` or `undefined`. To express that it can be null, use `a: string | null` (likewise for undefined). Specifying which parameters can be undefined/null saves a lot of runtime errors that are catched by the compiler.

If it is not clear what the type is, one can just use `any`. Of course, you lose opportunity for type checkers there.

**Comment by nikku** [comment]
Thanks for the clarification.

**Comment by nikku** [comment]
Merged via https://github.com/bpmn-io/min-dom/commit/e26242ce5887f93a30ac6e2b4aa791eafd23de7e and released as `v3.1.0`.

**Pull request closed without merging**
